###**Renewable Energy & Sustainability Data Analysis**

In [26]:
import pandas as pd
import numpy as np

In [27]:
df = pd.read_csv("complete_renewable_energy_dataset_missing.csv")

df.head()

,Country,Year,Energy Type,Production (GWh),Installed Capacity (MW),Investments (USD),Population,GDP,Energy Consumption,Energy Exports,...,Economic Freedom Index,Ease of Doing Business,Innovation Index,Number of Research Institutions,Number of Renewable Energy Conferences,Number of Renewable Energy Publications,Energy Sector Workforce,Proportion of Energy from Renewables,Public-Private Partnerships in Energy,Regional Renewable Energy Cooperation
0,USA,2011,Solar,85404.69003,5549.794323,5.604125e+09,1.064007e+09,1.780000e+14,369654.6442,93087.198200,...,49.216800,57.678605,76.803228,851,75,6361,511658,25.907895,1,0
1,Australia,2008,Geothermal,22205.06938,43211.593800,6.361886e+08,1.033256e+09,6.440000e+13,771781.6363,1752.536054,...,79.990942,1.761579,48.697825,590,39,9752,974948,95.003547,0,1
2,Canada,2013,Biomass,NaN,6139.117212,6.158680e+09,1.489512e+07,1.570000e+14,342707.1529,65146.592500,...,94.374040,77.657334,67.334813,101,7,311,326318,67.354539,1,0
3,Japan,2010,Biomass,88771.93291,40323.639260,8.526116e+09,1.448827e+09,1.350000e+14,498839.5743,50257.591010,...,65.143472,44.987734,4.544289,327,3,7708,506078,33.754104,0,0
4,China,2018,Solar,93288.40858,30755.403060,5.086237e+09,1.499494e+09,8.680000e+13,819064.3628,63101.395560,...,86.213626,62.535223,10.287199,985,69,4919,187964,59.509228,1,0

In [28]:
print(df.shape)

(2500, 56)

  - Dataset contains 2500 records and 56 features.
  - It represents renewable energy and sustainability indicators across different countries and years.

In [29]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 56 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Country                                  2500 non-null   object
 1   Year                                     2500 non-null   int64
 2   Energy Type                              2498 non-null   object
 3   Production (GWh)                         2499 non-null   float64
 4   Installed Capacity (MW)                  2500 non-null   float64
 5   Investments (USD)                        2500 non-null   float64
 6   Population                               2499 non-null   float64
 7   GDP                                      2500 non-null   float64
 8   Energy Consumption                       2500 non-null   float64
 9   Energy Exports                           2500 non-null   float64
 10  Energy Imports                           2500 non-null   float64
 11  CO2 Emissions                            2500 non-null   float64
 12  Renewable Energy Jobs                    2500 non-null   int64
 13  Government Policies                      2500 non-null   int64
 14  R&D Expenditure                          2500 non-null   float64
 15  Renewable Energy Targets                 2500 non-null   int64
 16  Average Annual Temperature               2500 non-null   float64
 17  Annual Rainfall                          2500 non-null   float64
 18  Solar Irradiance                         2500 non-null   float64
 19  Wind Speed                               2500 non-null   float64
 20  Hydro Potential                          2500 non-null   float64
 21  Geothermal Potential                     2500 non-null   float64
 22  Biomass Availability                     2500 non-null   float64
 23  Energy Storage Capacity                  2500 non-null   float64
 24  Grid Integration Capability              2500 non-null   float64
 25  Electricity Prices                       2500 non-null   float64
 26  Energy Subsidies                         2500 non-null   float64
 27  International Aid for Renewables         2500 non-null   float64
 28  Public Awareness                         2500 non-null   float64
 29  Energy Efficiency Programs               2500 non-null   int64
 30  Urbanization Rate                        2500 non-null   float64
 31  Industrialization Rate                   2500 non-null   float64
 32  Energy Market Liberalization             2500 non-null   int64
 33  Renewable Energy Patents                 2500 non-null   int64
 34  Educational Level                        2500 non-null   float64
 35  Technology Transfer Agreements           2500 non-null   int64
 36  Renewable Energy Education Programs      2500 non-null   int64
 37  Local Manufacturing Capacity             2500 non-null   float64
 38  Import Tariffs on Energy Equipment       2500 non-null   float64
 39  Export Incentives for Energy Equipment   2500 non-null   float64
 40  Natural Disasters                        2500 non-null   int64
 41  Political Stability                      2500 non-null   float64
 42  Corruption Perception Index              2500 non-null   float64
 43  Regulatory Quality                       2500 non-null   float64
 44  Rule of Law                              2500 non-null   float64
 45  Control of Corruption                    2500 non-null   float64
 46  Economic Freedom Index                   2500 non-null   float64
 47  Ease of Doing Business                   2500 non-null   float64
 48  Innovation Index                         2500 non-null   float64
 49  Number of Research Institutions          2500 non-null   int64
 50  Number of Renewable Energy Conferences   2500 non-null   int64
 51  Number of Renewable Energy Publications  2500 non-null   int64
 52  Energy Sector Workforce                  2500 non-null   int64
 53  Proportion of Energy from Renewables     2500 non-null   float64
 54  Public-Private Partnerships in Energy    2500 non-null   int64
 55  Regional Renewable Energy Cooperation    2500 non-null   int64
dtypes: float64(38), int64(16), object(2)
memory usage: 1.1+ MB
None

In [30]:
print(df.describe())

              Year  Production (GWh)  Installed Capacity (MW)  \
count  2500.000000       2499.000000              2500.000000
mean   2011.437600      48725.043998             24882.910674
std       6.895471      28332.049485             14463.459958
min    2000.000000       1053.354158               114.531639
25%    2006.000000      24307.893805             12282.213158
50%    2011.000000      47341.460670             24689.162460
75%    2017.250000      73028.524390             37438.443573
max    2023.000000      99937.503720             49997.387580

       Investments (USD)    Population           GDP  Energy Consumption  \
count       2.500000e+03  2.499000e+03  2.500000e+03         2500.000000
mean        4.956155e+09  7.460187e+08  1.010717e+14       495701.245158
std         2.894789e+09  4.373568e+08  5.782829e+13       291419.017956
min         5.886994e+06  1.255357e+06  5.603965e+10         1264.851083
25%         2.473145e+09  3.719678e+08  5.050000e+13       237300.546575
50%         4.961772e+09  7.517937e+08  1.030000e+14       496118.165250
75%         7.418384e+09  1.118071e+09  1.520000e+14       753779.282800
max         9.998292e+09  1.499494e+09  2.000000e+14       999618.512200

       Energy Exports  Energy Imports  CO2 Emissions  ...  \
count     2500.000000     2500.000000    2500.000000  ...
mean     50143.392627    50800.373871  491218.412643  ...
std      28833.333066    28740.851763  289783.733338  ...
min       1036.618008     1057.783513    1124.768458  ...
25%      25146.745295    26347.461048  242894.720500  ...
50%      49706.656935    50698.800025  475721.007850  ...
75%      75567.191518    75807.642497  747649.446325  ...
max      99952.509820    99912.213810  999816.500200  ...

       Economic Freedom Index  Ease of Doing Business  Innovation Index  \
count             2500.000000             2500.000000       2500.000000
mean                50.736720               48.442085         50.280019
std                 28.623766               28.798216         28.719483
min                  0.104915                0.025281          0.025733
25%                 26.241437               23.519814         25.934406
50%                 50.850766               48.127673         51.398964
75%                 74.908485               73.324825         74.724073
max                 99.970526               99.901347         99.998838

       Number of Research Institutions  \
count                      2500.000000
mean                        496.660400
std                         296.181011
min                           0.000000
25%                         234.000000
50%                         493.000000
75%                         755.000000
max                         999.000000

       Number of Renewable Energy Conferences  \
count                             2500.000000
mean                                50.431200
std                                 28.877168
min                                  0.000000
25%                                 26.000000
50%                                 51.000000
75%                                 76.000000
max                                 99.000000

       Number of Renewable Energy Publications  Energy Sector Workforce  \
count                               2500.00000              2500.000000
mean                                4978.93360            502040.891200
std                                 2881.93256            293084.636148
min                                    3.00000               494.000000
25%                                 2532.00000            244438.000000
50%                                 4992.50000            499151.000000
75%                                 7465.00000            765088.000000
max                                 9999.00000            999226.000000

       Proportion of Energy from Renewables  \
count                           2500.000000
mean                              49.749110
std                               28.924307
min                                0.033829
25%                               23.968451
50%                               50.232069
75%                               74.354781
max                               99.988355

       Public-Private Partnerships in Energy  \
count                            2500.000000
mean                                0.512000
std                                 0.499956
min                                 0.000000
25%                                 0.000000
50%                                 1.000000
75%                                 1.000000
max                                 1.000000

       Regional Renewable Energy Cooperation
count                            2500.000000
mean                                0.473600
std                                 0.499402
min                                 0.000000
25%                                 0.000000
50%                                 0.000000
75%                                 1.000000
max                                 1.000000

[8 rows x 54 columns]

In [31]:
print(df.dtypes)

Country                                     object
Year                                         int64
Energy Type                                 object
Production (GWh)                           float64
Installed Capacity (MW)                    float64
Investments (USD)                          float64
Population                                 float64
GDP                                        float64
Energy Consumption                         float64
Energy Exports                             float64
Energy Imports                             float64
CO2 Emissions                              float64
Renewable Energy Jobs                        int64
Government Policies                          int64
R&D Expenditure                            float64
Renewable Energy Targets                     int64
Average Annual Temperature                 float64
Annual Rainfall                            float64
Solar Irradiance                           float64
Wind Speed                                 float64
Hydro Potential                            float64
Geothermal Potential                       float64
Biomass Availability                       float64
Energy Storage Capacity                    float64
Grid Integration Capability                float64
Electricity Prices                         float64
Energy Subsidies                           float64
International Aid for Renewables           float64
Public Awareness                           float64
Energy Efficiency Programs                   int64
Urbanization Rate                          float64
Industrialization Rate                     float64
Energy Market Liberalization                 int64
Renewable Energy Patents                     int64
Educational Level                          float64
Technology Transfer Agreements               int64
Renewable Energy Education Programs          int64
Local Manufacturing Capacity               float64
Import Tariffs on Energy Equipment         float64
Export Incentives for Energy Equipment     float64
Natural Disasters                            int64
Political Stability                        float64
Corruption Perception Index                float64
Regulatory Quality                         float64
Rule of Law                                float64
Control of Corruption                      float64
Economic Freedom Index                     float64
Ease of Doing Business                     float64
Innovation Index                           float64
Number of Research Institutions              int64
Number of Renewable Energy Conferences       int64
Number of Renewable Energy Publications      int64
Energy Sector Workforce                      int64
Proportion of Energy from Renewables       float64
Public-Private Partnerships in Energy        int64
Regional Renewable Energy Cooperation        int64
dtype: object

In [32]:
print(df.isnull().sum())

Country                                    0
Year                                       0
Energy Type                                2
Production (GWh)                           1
Installed Capacity (MW)                    0
Investments (USD)                          0
Population                                 1
GDP                                        0
Energy Consumption                         0
Energy Exports                             0
Energy Imports                             0
CO2 Emissions                              0
Renewable Energy Jobs                      0
Government Policies                        0
R&D Expenditure                            0
Renewable Energy Targets                   0
Average Annual Temperature                 0
Annual Rainfall                            0
Solar Irradiance                           0
Wind Speed                                 0
Hydro Potential                            0
Geothermal Potential                       0
Biomass Availability                       0
Energy Storage Capacity                    0
Grid Integration Capability                0
Electricity Prices                         0
Energy Subsidies                           0
International Aid for Renewables           0
Public Awareness                           0
Energy Efficiency Programs                 0
Urbanization Rate                          0
Industrialization Rate                     0
Energy Market Liberalization               0
Renewable Energy Patents                   0
Educational Level                          0
Technology Transfer Agreements             0
Renewable Energy Education Programs        0
Local Manufacturing Capacity               0
Import Tariffs on Energy Equipment         0
Export Incentives for Energy Equipment     0
Natural Disasters                          0
Political Stability                        0
Corruption Perception Index                0
Regulatory Quality                         0
Rule of Law                                0
Control of Corruption                      0
Economic Freedom Index                     0
Ease of Doing Business                     0
Innovation Index                           0
Number of Research Institutions            0
Number of Renewable Energy Conferences     0
Number of Renewable Energy Publications    0
Energy Sector Workforce                    0
Proportion of Energy from Renewables       0
Public-Private Partnerships in Energy      0
Regional Renewable Energy Cooperation      0
dtype: int64

Observation:

The dataset contains a few missing values in the following columns:

  - Energy Type
  - Production (GWh)
  - Population

Since these missing values are very few compared to the total dataset size (2500 records), they can be handled without affecting the overall analysis.

Categorical values will be filled using the Mode, while numerical values will be filled using the Mean.

In [33]:
# Handling Missing Values

df["Energy Type"] = df["Energy Type"].fillna(df["Energy Type"].mode()[0])

df["Production (GWh)"] = df["Production (GWh)"].fillna(df["Production (GWh)"].mean())

df["Population"] = df["Population"].fillna(df["Population"].mean())

  - The missing values have been successfully handled.

  - Mode was used for the categorical feature 'Energy Type' because it replaces missing values with the most frequent category.

  - Mean was used for the numerical features 'Production (GWh)' and 'Population' because it preserves the overall average of the dataset.

In [34]:
print(df.isnull().sum())

Country                                    0
Year                                       0
Energy Type                                0
Production (GWh)                           0
Installed Capacity (MW)                    0
Investments (USD)                          0
Population                                 0
GDP                                        0
Energy Consumption                         0
Energy Exports                             0
Energy Imports                             0
CO2 Emissions                              0
Renewable Energy Jobs                      0
Government Policies                        0
R&D Expenditure                            0
Renewable Energy Targets                   0
Average Annual Temperature                 0
Annual Rainfall                            0
Solar Irradiance                           0
Wind Speed                                 0
Hydro Potential                            0
Geothermal Potential                       0
Biomass Availability                       0
Energy Storage Capacity                    0
Grid Integration Capability                0
Electricity Prices                         0
Energy Subsidies                           0
International Aid for Renewables           0
Public Awareness                           0
Energy Efficiency Programs                 0
Urbanization Rate                          0
Industrialization Rate                     0
Energy Market Liberalization               0
Renewable Energy Patents                   0
Educational Level                          0
Technology Transfer Agreements             0
Renewable Energy Education Programs        0
Local Manufacturing Capacity               0
Import Tariffs on Energy Equipment         0
Export Incentives for Energy Equipment     0
Natural Disasters                          0
Political Stability                        0
Corruption Perception Index                0
Regulatory Quality                         0
Rule of Law                                0
Control of Corruption                      0
Economic Freedom Index                     0
Ease of Doing Business                     0
Innovation Index                           0
Number of Research Institutions            0
Number of Renewable Energy Conferences     0
Number of Renewable Energy Publications    0
Energy Sector Workforce                    0
Proportion of Energy from Renewables       0
Public-Private Partnerships in Energy      0
Regional Renewable Energy Cooperation      0
dtype: int64

  - All missing values have been successfully removed.

  - The dataset now contains no null values and is ready for generalization, feature relationship analysis, and further data exploration.

###**Generalization**

In [35]:
df.groupby("Energy Type")["Production (GWh)"].mean()

Energy Type
Biomass       50161.800911
Geothermal    48369.628108
Hydro         49110.669847
Solar         47090.964755
Wind          48964.172324
Name: Production (GWh), dtype: float64

  - Different renewable energy sources contribute differently to energy production.

In [36]:
df.groupby("Country")["CO2 Emissions"].mean()

Country
Australia    530626.138447
Brazil       479033.801729
Canada       496632.736260
China        465664.867708
France       511570.231226
Germany      483283.488638
India        450928.040920
Japan        512328.833981
Russia       496143.595367
USA          483573.925621
Name: CO2 Emissions, dtype: float64

  - CO₂ emissions vary significantly among countries.

In [37]:
df.groupby("Country")["Proportion of Energy from Renewables"].mean()

Country
Australia    52.716070
Brazil       45.998987
Canada       48.803394
China        48.115621
France       50.893399
Germany      51.161707
India        49.626270
Japan        49.131578
Russia       50.877819
USA          50.030260
Name: Proportion of Energy from Renewables, dtype: float64

  - Some countries depend much more on renewable energy than others.

In [38]:
df[["Production (GWh)",
    "Installed Capacity (MW)"]].corr()

                         Production (GWh)  Installed Capacity (MW)
Production (GWh)                 1.000000                -0.030069
Installed Capacity (MW)         -0.030069                 1.000000

  - Higher installed capacity generally results in higher energy production.

In [39]:
df[["GDP",
    "Investments (USD)"]].corr()

                        GDP  Investments (USD)
GDP                1.000000          -0.027842
Investments (USD) -0.027842           1.000000

  - Countries with higher GDP tend to invest more in renewable energy.

In [40]:
df[["Energy Consumption",
    "CO2 Emissions"]].corr()

                    Energy Consumption  CO2 Emissions
Energy Consumption            1.000000       0.026668
CO2 Emissions                 0.026668       1.000000

  - Higher energy consumption is generally associated with higher CO₂ emissions.

In [41]:
df[["Solar Irradiance",
    "Production (GWh)"]].corr()

                  Solar Irradiance  Production (GWh)
Solar Irradiance          1.000000          0.011326
Production (GWh)          0.011326          1.000000

  - Regions with greater solar irradiance have better potential for solar energy production.

In [42]:
df[["Wind Speed",
    "Production (GWh)"]].corr()

                  Wind Speed  Production (GWh)
Wind Speed           1.00000          -0.00695
Production (GWh)    -0.00695           1.00000

  - Wind speed positively influences wind energy generation.

In [43]:
df[["Hydro Potential",
    "Production (GWh)"]].corr()

                  Hydro Potential  Production (GWh)
Hydro Potential          1.000000          0.003816
Production (GWh)         0.003816          1.000000

  - Countries with high hydro potential can generate more hydroelectric energy.

In [44]:
df.groupby("Energy Type")["Renewable Energy Jobs"].sum()

Energy Type
Biomass       249434929
Geothermal    263048757
Hydro         236168747
Solar         249516591
Wind          259071185
Name: Renewable Energy Jobs, dtype: int64

  - Different renewable energy sectors create different numbers of employment opportunities.

In [45]:
df.groupby("Country")["Energy Consumption"].mean()

Country
Australia    469529.093698
Brazil       476372.249146
Canada       506239.271053
China        477611.421083
France       497681.347155
Germany      479086.429906
India        509943.300295
Japan        546051.932007
Russia       498915.691792
USA          495484.292344
Name: Energy Consumption, dtype: float64

  - Energy consumption differs among countries due to population and industrial development.

In [46]:
df[["Population",
    "Energy Consumption"]].corr()

                    Population  Energy Consumption
Population            1.000000           -0.006132
Energy Consumption   -0.006132            1.000000

  - Population has a positive relationship with energy consumption.

In [47]:
df[["Government Policies",
    "Renewable Energy Targets"]].corr()

                          Government Policies  Renewable Energy Targets
Government Policies                  1.000000                 -0.031023
Renewable Energy Targets            -0.031023                  1.000000

  - Strong government policies support higher renewable energy targets.

In [48]:
df[["Innovation Index",
    "Renewable Energy Patents"]].corr()

                          Innovation Index  Renewable Energy Patents
Innovation Index                   1.00000                  -0.00999
Renewable Energy Patents          -0.00999                   1.00000

  - Countries with higher innovation tend to produce more renewable energy patents.

In [49]:
df.sort_values("Production (GWh)",ascending=False).head(10)

,Country,Year,Energy Type,Production (GWh),Installed Capacity (MW),Investments (USD),Population,GDP,Energy Consumption,Energy Exports,...,Economic Freedom Index,Ease of Doing Business,Innovation Index,Number of Research Institutions,Number of Renewable Energy Conferences,Number of Renewable Energy Publications,Energy Sector Workforce,Proportion of Energy from Renewables,Public-Private Partnerships in Energy,Regional Renewable Energy Cooperation
354,Japan,2014,Geothermal,99937.50372,31311.519200,2.174339e+09,1.316926e+09,7.010000e+13,794551.3494,36111.45686,...,16.209390,61.943993,30.362324,85,92,7900,623387,31.486383,0,1
417,Canada,2012,Hydro,99925.06126,26824.443710,3.439820e+09,4.818766e+08,3.160000e+13,743320.0954,70251.62948,...,46.312650,8.445713,27.288953,223,53,6761,361509,96.684699,0,0
1378,China,2010,Geothermal,99917.75179,14228.977590,9.365604e+09,3.764033e+08,1.560000e+14,857484.5112,39928.84944,...,6.107815,93.058836,47.147257,90,61,5332,15482,93.052637,0,0
747,Brazil,2017,Solar,99861.15067,1952.904794,1.046081e+09,6.251455e+08,1.360000e+14,335391.2960,98429.01855,...,17.009339,96.024376,96.864249,939,94,6527,203929,41.571228,0,0
1389,France,2011,Wind,99702.81341,18485.979180,4.491185e+09,1.361965e+09,1.410000e+14,318730.4957,68836.53962,...,30.633119,27.185703,89.610116,248,62,3729,257938,94.231883,1,1
330,Canada,2023,Biomass,99702.73827,31441.117840,8.859843e+09,7.693082e+08,1.160000e+14,272077.9316,10170.27704,...,39.775839,51.738605,60.910864,51,55,9384,149265,95.338323,1,1
1545,India,2011,Wind,99696.60640,32732.963050,3.498935e+09,4.320031e+07,9.400000e+13,799920.8030,92446.73722,...,84.640691,58.020015,93.238310,27,42,4977,483533,64.069888,0,0
989,USA,2004,Wind,99685.26471,2533.960864,8.965256e+09,2.217106e+07,1.730000e+14,321090.7352,69610.79025,...,46.693949,12.795010,62.146931,808,79,5667,877698,36.789919,1,0
960,Germany,2020,Geothermal,99645.58064,870.662981,6.751843e+09,1.970290e+08,3.180000e+13,919120.3598,76144.17202,...,83.509614,40.624918,14.895705,67,71,1149,773759,73.861770,0,0
1886,Germany,2018,Geothermal,99625.17485,33038.520320,9.462739e+09,6.411768e+08,1.750000e+14,520621.3702,70773.05044,...,58.823583,75.835404,67.865158,218,13,8885,889036,58.124289,0,1

  - These are the highest renewable energy producers in the dataset.

###**Summary**

1. Imported the Renewable Energy and Sustainability dataset using the Pandas library.

2. Explored the dataset by examining its shape, data types, column information, and statistical summary.

3. Checked the dataset for missing values and identified null values in a few numerical and categorical columns.

4. Handled missing values appropriately by replacing:
    - Numerical missing values with the Mean.
    - Categorical missing values with the Mode.

5. Verified that all missing values were successfully removed, making the dataset clean and ready for analysis.

6. Performed feature-wise analysis to understand relationships between important sustainability indicators such as energy production, renewable energy share, CO₂ emissions, GDP, population, government policies, innovation, and employment.

7. Generated meaningful insights and generalizations using grouping, correlation, and statistical analysis to better understand renewable energy trends and sustainability factors.

8. Concluded that renewable energy development is strongly influenced by factors such as investment, installed capacity, government policies, innovation, and population, while increased adoption of renewable energy contributes to improved sustainability and reduced environmental impact.

Overall, this analysis demonstrates the complete data analysis workflow, including data exploration, preprocessing, missing value handling, feature relationship analysis, and interpretation of sustainability-related insights.